# NOTE: https://github.com/devJRL/CodeLab-Docker-Kubernetes/tree/master/kubectl#pod
apiVersion: v1
kind: Pod
metadata:
  name: codelab-simple-pod
spec:
  containers:
    #1
    - name: web-apache
      image: dev2sponge/codelab-k8s-apache:1.0.0
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64M" # = 64 MB
          cpu: "250m" # = 0.25 vCPU
        limits:
          memory: "128M" # = 128 MB
          cpu: "500m" # = 0.5 vCPU
    #2
    - name: was-tomcat
      image: dev2sponge/codelab-k8s-tomcat:1.0.0
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "64Mi" # = 2^26 byte (129MB)
          cpu: "250m" # = 0.25 vCPU
        limits:
          memory: "128Mi" # = 2^27 byte (259MB)
          cpu: "500m" # = 0.5 vCPU
