# ---------------------------------------
# *****  ALERT! DON'T USE IN PROD!  *****
# *****    JUST FOR STUDY IMAGE     *****
# ---------------------------------------
FROM nginx:latest

COPY ./conf/ /etc/nginx

COPY ./public-html/ /usr/share/nginx/html
