# ---------------------------------------
# *****  ALERT! DON'T USE IN PROD!  *****
# *****    JUST FOR STUDY IMAGE     *****
# ---------------------------------------
FROM tomcat:9

RUN ["mkdir", "/usr/local/tomcat/webapps/ROOT"]
COPY ./public-html/ /usr/local/tomcat/webapps/ROOT/
